# streamlit_app.py

# ============================
#   RETAIL DEMAND DASHBOARD
# ============================

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

def smape(actual, forecast):
    actual = pd.Series(actual)
    forecast = pd.Series(forecast)
    return (200 * (abs(actual - forecast) / (abs(actual) + abs(forecast) + 1e-8))).mean()


# ---------------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------------
st.set_page_config(
    page_title="Retail Demand Forecasting Dashboard",
    page_icon="📈",
    layout="wide"
)

st.markdown("""
<style>

/* ---------------------------------------
   GREY SIDEBAR BACKGROUND
----------------------------------------*/
[data-testid="stSidebar"] {
    background-color: #3a3a3a !important;   /* medium-light grey */
    min-width: 230px !important;
    max-width: 230px !important;
    padding-top: 1rem !important;
    color: #ffffff !important;
}

/* Sidebar title ("Go to") */
[data-testid="stSidebar"] h1,
[data-testid="stSidebar"] h2,
[data-testid="stSidebar"] h3,
[data-testid="stSidebar"] p {
    color: #ffffff !important;
}

/* ---------------------------------------
   SIDEBAR RADIO LABEL TEXT
----------------------------------------*/
[data-testid="stSidebar"] label {
    color: #ffffff !important;        /* bright white text */
    font-size: 15px !important;
    white-space: nowrap !important;
    text-overflow: ellipsis !important;
}

/* Icons next to labels */
[data-testid="stSidebar"] label span {
    color: #ffffff !important;
    font-size: 16px !important;
}

/* ---------------------------------------
   SELECTED MENU OPTION (HIGHLIGHT)
----------------------------------------*/
.st-emotion-cache-1y4p8pa {
    background-color: #555555 !important;   /* lighter grey highlight */
    color: #ffffff !important;
    border-radius: 6px;
    padding: 6px 10px;
}

/* Selected radio dot */
.st-bf {
    background-color: #4CAF50 !important;  
}

/* Unselected radio circle outline */
.st-b8 {
    border-color: #ffffff !important;
}

/* Hover effect */
[data-testid="stSidebar"] label:hover {
    color: #e0e0e0 !important;
}

/* ---------------------------------------
   MAIN CONTENT SPACING
----------------------------------------*/
.block-container {
    padding-top: 1rem !important;
    padding-left: 2rem !important;
    padding-right: 2rem !important;
}

/* ---------------------------------------
   TABLE COMPACT STYLING
----------------------------------------*/
.dataframe tbody tr td,
.dataframe tbody tr th {
    padding: 4px 8px !important;
    font-size: 13px !important;
}

.dataframe thead th {
    background-color: #f3f3f3 !important;
    color: #333 !important;
    padding: 6px 8px !important;
}
</style>
""", unsafe_allow_html=True)


# ---------------------------------------------------------
# PAGE TITLE
# ---------------------------------------------------------
st.title("Retail Demand Forecasting Dashboard")

st.write(
    "This dashboard helps demand planners visualize and interpret daily "
    "sales forecasts generated by the LightGBM model. It focuses on "
    "store-level demand, seasonality, and planning for replenishment, "
    "promotions, and inventory alignment."
)

# ---------------------------------------------------------
# GLOBAL PATHS
# ---------------------------------------------------------
METRIC_PATH = "deployment/"
FORECAST_FILE = "forecast_results.csv"
STORE_FORECAST_FILE = METRIC_PATH + "lightgbm_val_predictions.csv"


# ---------------------------------------------------------
# UTILITY: NORMALIZE METRICS
# ---------------------------------------------------------
def fix_keys(d: dict) -> dict:
    return {
        "RMSE": float(d.get("RMSE")),
        "MAPE": float(d.get("MAPE") or d.get("MAPE (%)")),
        "WAPE": float(d.get("WAPE") or d.get("WAPE (%)")),
    }


# ---------------------------------------------------------
# LOAD METRICS
# ---------------------------------------------------------
@st.cache_data
def load_metrics():
    try:
        baseline = fix_keys(pd.read_pickle(METRIC_PATH + "baseline_metrics.pkl"))
        arima = fix_keys(pd.read_pickle(METRIC_PATH + "arima_metrics.pkl"))
        sarima = fix_keys(pd.read_pickle(METRIC_PATH + "sarima_metrics.pkl"))
        lightgbm = fix_keys(pd.read_pickle(METRIC_PATH + "lightgbm_metrics.pkl"))
    except Exception as e:
        st.error(f"❌ Error loading metric files: {e}")
        return None

    return pd.DataFrame([        
        {"MODEL": "Baseline", **baseline},
        {"MODEL": "ARIMA", **arima},
        {"MODEL": "SARIMA", **sarima},
        {"MODEL": "LightGBM", **lightgbm}
    ]).round(2)


# ---------------------------------------------------------
# LOAD CHAIN FORECAST
# ---------------------------------------------------------
@st.cache_data
def load_chain_forecast():
    try:
        df = pd.read_csv(FORECAST_FILE)
    except Exception as e:
        st.warning(f"⚠️ Could not load {FORECAST_FILE}: {e}")
        return None

    df.columns = [c.lower() for c in df.columns]
    df = df.rename(columns={"date": "Date", "actual": "Actual", "forecast": "Forecast"})
    df["Date"] = pd.to_datetime(df["Date"])
    return df


# ---------------------------------------------------------
# LOAD STORE FORECAST
# ---------------------------------------------------------
@st.cache_data
def load_store_forecast():
    try:
        df = pd.read_csv(STORE_FORECAST_FILE)
    except Exception as e:
        st.warning(f"⚠️ Could not load store-level forecast: {e}")
        return None

    df.columns = [c.lower() for c in df.columns]

    df = df.rename(columns={
        "date": "Date",
        "store": "Store",
        "store_id": "Store",
        "sales": "Sales",
        "actual": "Sales"
    })

    pred_col = next((c for c in df.columns if "pred" in c or "forecast" in c), None)
    df["Prediction"] = df[pred_col] if pred_col else np.nan
    df["Date"] = pd.to_datetime(df["Date"])

    return df


# ---------------------------------------------------------
# OVERVIEW PAGE
# ---------------------------------------------------------
def page_overview():
    st.subheader("📊 Model Performance Overview")

    df = load_metrics()
    if df is None:
        st.stop()

    best = df[df["MODEL"] == "LightGBM"].iloc[0]

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("🏆 Best Model", "LightGBM")
    c2.metric("RMSE", f"{best['RMSE']:.2f}")
    c3.metric("MAPE (%)", f"{best['MAPE']:.2f}")
    c4.metric("WAPE (%)", f"{best['WAPE']:.2f}")

    st.markdown("### 📘 Full Model Comparison Table")
    # Format numbers to 2 decimal places
    df_display = df.copy()
    numeric_cols = df_display.select_dtypes(include=[float, int]).columns
    df_display[numeric_cols] = df_display[numeric_cols].astype(float).round(2)

    st.dataframe(df_display, use_container_width=True)



# ---------------------------------------------------------
# CHAIN FORECAST PAGE
# ---------------------------------------------------------
def page_chain_forecast():
    st.subheader("📈 Average Sales Across All Stores")

    df = load_chain_forecast()
    if df is None:
        st.stop()

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=df["Date"], y=df["Actual"], name="Actual", line=dict(color="orange")))
    fig.add_trace(go.Scatter(x=df["Date"], y=df["Forecast"], name="Forecast", line=dict(color="steelblue", dash="dash")))

    fig.update_layout(template="plotly_white", height=450)
    st.plotly_chart(fig, use_container_width=True)

    d2 = df.dropna()
    rmse = np.sqrt(np.mean((d2["Actual"] - d2["Forecast"])**2))
    mape = np.mean(np.abs(d2["Actual"] - d2["Forecast"]) / d2["Actual"]) * 100

    c1, c2 = st.columns(2)
    c1.metric("Chain RMSE", f"{rmse:,.2f}")
    c2.metric("Chain MAPE", f"{mape:,.2f}%")


# ---------------------------------------------------------
# STORE EXPLORER PAGE
# ---------------------------------------------------------
def page_store_explorer():
    st.subheader("🏬 Store-Level Forecast Explorer")

    df = load_store_forecast()
    if df is None:
        st.stop()

    store_id = st.selectbox("Select Store", sorted(df["Store"].unique()))
    store_df = df[df["Store"] == store_id].sort_values("Date")

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=store_df["Date"], y=store_df["Sales"], name="Actual", line=dict(color="orange")))
    fig.add_trace(go.Scatter(x=store_df["Date"], y=store_df["Prediction"], name="Forecast", line=dict(color="steelblue", dash="dash")))

    fig.update_layout(template="plotly_white", height=450)
    st.plotly_chart(fig, use_container_width=True)

    d2 = store_df.dropna()
    rmse = np.sqrt(np.mean((d2["Sales"] - d2["Prediction"])**2))
    smape_value = smape(d2["Sales"], d2["Prediction"])

    c1, c2 = st.columns(2)
    c1.metric("Store RMSE", f"{rmse:,.2f}")
    c2.metric("Store SMAPE", f"{smape_value:,.2f}%")

    st.expander("Show Raw Store Data").dataframe(store_df, use_container_width=True)


# ---------------------------------------------------------
# DATA PREVIEW & DOWNLOADS
# ---------------------------------------------------------
def page_data_downloads():
    st.subheader("📂 Data Preview & Downloads")

    metrics_df = load_metrics()
    chain_df = load_chain_forecast()
    store_df = load_store_forecast()

    # ---------------------------------
    # MODEL METRICS (NO DOWNLOAD BUTTON)
    # ---------------------------------
    st.markdown("### 📊 Model Metrics")
    st.dataframe(metrics_df, use_container_width=True)

    # ---------------------------------
    # CHAIN FORECAST + SMALL RIGHT BUTTON
    # ---------------------------------
    st.markdown("### 🔗 Chain Forecast")

    # Small right-aligned download button
    chain_csv = chain_df.to_csv(index=False).encode("utf-8")
    st.markdown(
        "<div style='text-align:right;'>"
        "<a download='chain_forecast.csv' "
        "href='data:text/csv;base64," + chain_csv.decode("latin1") + "' "
        "style='background:#d9d9d9;padding:6px 12px;border-radius:6px;"
        "text-decoration:none;color:black;font-size:12px;'>⬇ Download</a>"
        "</div>",
        unsafe_allow_html=True
    )

    st.dataframe(chain_df.head(), use_container_width=True)

    # ---------------------------------
    # STORE FORECAST + SMALL RIGHT BUTTON
    # ---------------------------------
    st.markdown("### 🏬 Store Forecast")

    store_csv = store_df.to_csv(index=False).encode("utf-8")
    st.markdown(
        "<div style='text-align:right;'>"
        "<a download='store_forecast.csv' "
        "href='data:text/csv;base64," + store_csv.decode("latin1") + "' "
        "style='background:#d9d9d9;padding:6px 12px;border-radius:6px;"
        "text-decoration:none;color:black;font-size:12px;'>⬇ Download</a>"
        "</div>",
        unsafe_allow_html=True
    )

    st.dataframe(store_df.head(), use_container_width=True)

# ---------------------------------------------------------
# SIDEBAR NAVIGATION WITH ICONS
# ---------------------------------------------------------
menu_icons = {
    "Overview": "📊",
    "Chain Forecast": "📈",
    "Store Explorer": "🏬",
    "Data & Downloads": "📂"
}

choice = st.sidebar.radio(
    "Go to",
    list(menu_icons.keys()),
    format_func=lambda x: f"{menu_icons[x]} {x}"
)

if choice == "Overview":
    page_overview()
elif choice == "Chain Forecast":
    page_chain_forecast()
elif choice == "Store Explorer":
    page_store_explorer()
elif choice == "Data & Downloads":
    page_data_downloads()
