import streamlit as st
import pandas as pd
import numpy as np
import pickle
import os

# -----------------------------
# CONFIG
# -----------------------------
DEPLOY_DIR = "deployment"

st.set_page_config(
    page_title="Retail Demand Forecasting Dashboard",
    layout="wide"
)

# -----------------------------
# DATA LOADERS  (cached)
# -----------------------------
@st.cache_data
def load_val_results():
    path = os.path.join(DEPLOY_DIR, "lightgbm_val_predictions.csv")
    df = pd.read_csv(path, parse_dates=["Date"])
    return df

@st.cache_data
def load_baseline_weekly():
    path = os.path.join(DEPLOY_DIR, "baseline_weekly_predictions.csv")
    df = pd.read_csv(path, parse_dates=["Date"])
    return df

@st.cache_data
def load_store1_weekly():
    path = os.path.join(DEPLOY_DIR, "store1_weekly_predictions.csv")
    df = pd.read_csv(path, parse_dates=["Date"])
    return df

@st.cache_data
def load_metrics():
    def load_pkl(name):
        with open(os.path.join(DEPLOY_DIR, name), "rb") as f:
            return pickle.load(f)

    baseline = load_pkl("baseline_metrics.pkl")
    arima    = load_pkl("arima_metrics.pkl")
    sarima   = load_pkl("sarima_metrics.pkl")
    lgbm     = load_pkl("lightgbm_metrics.pkl")

    metrics_df = pd.DataFrame([
        {"Model": "Baseline (7-day Lag)", **baseline},
        {"Model": "ARIMA (1,1,1)",       **arima},
        {"Model": "SARIMA",              **sarima},
        {"Model": "LightGBM",            **lgbm},
    ])

    # Rename columns for display
    metrics_df = metrics_df.rename(
        columns={
            "RMSE": "RMSE",
            "MAPE (%)": "MAPE (%)" if "MAPE (%)" in metrics_df.columns else "MAPE",
            "WAPE (%)": "WAPE (%)" if "WAPE (%)" in metrics_df.columns else "WAPE",
        }
    )

    return metrics_df

# -----------------------------
# LOAD DATA
# -----------------------------
val_df       = load_val_results()
baseline_w   = load_baseline_weekly()
store1_weekly = load_store1_weekly()
metrics_df   = load_metrics()

# Pre-compute overall series for overview charts
val_mean = (
    val_df.groupby("Date")[["Sales", "LGB_Pred"]]
    .mean()
    .reset_index()
    .rename(columns={"Sales": "Actual", "LGB_Pred": "Forecast"})
)

# -----------------------------
# SIDEBAR NAVIGATION
# -----------------------------
st.sidebar.title("Navigation")
page = st.sidebar.radio(
    "Go to",
    ["Overview", "Store Explorer", "Model Comparison", "Drivers of Demand (Explainability)"]
)

# -----------------------------
# PAGE 1: OVERVIEW
# -----------------------------
if page == "Overview":
    st.title("Retail Demand Forecasting Dashboard")
    st.markdown(
        """
        This dashboard helps demand planners **see and trust** the forecasts
        generated by the LightGBM model.  
        It focuses on daily store-level sales, seasonality, and planning
        for replenishment, promotions, and inventory alignment.
        """
    )

    # --- KPIs (using LightGBM + Baseline) ---
    lgb_row = metrics_df[metrics_df["Model"] == "LightGBM"].iloc[0]
    base_row = metrics_df[metrics_df["Model"] == "Baseline (7-day Lag)"].iloc[0]

    col1, col2, col3 = st.columns(3)
    col1.metric("LightGBM MAPE (%)", f"{lgb_row['MAPE (% )'] if 'MAPE (% )' in lgb_row else lgb_row['MAPE']:0.2f}")
    col2.metric("LightGBM WAPE (%)", f"{lgb_row['WAPE (% )'] if 'WAPE (% )' in lgb_row else lgb_row['WAPE']:0.2f}")
    improvement = base_row["MAPE"] - (lgb_row.get("MAPE (% )", lgb_row.get("MAPE")))
    col3.metric("Error reduction vs Baseline (MAPE)", f"{improvement:0.2f} pts")

    st.markdown("---")

    # --- Chain-level Actual vs Forecast ---
    st.subheader("Average Sales Across All Stores: Actual vs Forecast")
    st.line_chart(
        val_mean.set_index("Date")[["Actual", "Forecast"]]
    )

    st.caption(
        "The orange and blue lines should move closely together. "
        "The closer they are, the more accurate the model is at capturing "
        "overall demand patterns across the chain."
    )
st.write("DEBUG - Metrics DF:", metrics_df)

# -----------------------------
# PAGE 2: STORE EXPLORER
# -----------------------------
elif page == "Store Explorer":
    st.title("Store-level Forecast Explorer")

    store_list = sorted(val_df["Store"].unique())
    store_id = st.selectbox("Select a Store", store_list)

    store_data = (
        val_df[val_df["Store"] == store_id]
        .sort_values("Date")
        .copy()
    )
    store_data = store_data.rename(columns={"Sales": "Actual", "LGB_Pred": "Forecast"})
    store_data = store_data.set_index("Date")

    st.subheader(f"Actual vs Forecasted Sales – Store {store_id}")
    st.line_chart(store_data[["Actual", "Forecast"]])

    st.caption(
        "This view helps planners quickly see if a specific store is "
        "tracking above or below the forecast, and spot unusual dips or spikes."
    )

    # Simple daily error table
    store_data["Absolute Error"] = (store_data["Actual"] - store_data["Forecast"]).abs()
    st.subheader("Daily Forecast Error (Store Level)")
    st.dataframe(store_data[["Actual", "Forecast", "Absolute Error"]].tail(30))

# -----------------------------
# PAGE 3: MODEL COMPARISON
# -----------------------------
elif page == "Model Comparison":
    st.title("Model Performance Comparison")

    st.markdown(
        """
        This section compares the **baseline**, **ARIMA**, **SARIMA**, and **LightGBM**
        models using standard forecasting metrics.  
        Lower values mean better performance.
        """
    )

    # Display metrics table
    st.dataframe(metrics_df.style.format({"RMSE": "{:,.2f}", "MAPE": "{:,.2f}", "WAPE": "{:,.2f}"}))

    st.markdown("---")
    st.subheader("Weekly Forecast – Store 1 (ARIMA vs SARIMA)")

    chart_df = store1_weekly.copy()
    chart_df = chart_df.rename(columns={"Sales": "Actual"})
    chart_df = chart_df.set_index("Date")

    st.line_chart(chart_df[["Actual", "ARIMA_Forecast", "SARIMA_Forecast"]])

    st.caption(
        "Here we see how classical ARIMA/SARIMA models perform on weekly Store 1 data. "
        "Despite reasonable performance, LightGBM offers better flexibility and scalability "
        "for all stores and daily forecasts."
    )

# -----------------------------
# PAGE 4: DRIVERS OF DEMAND
# -----------------------------
elif page == "Drivers of Demand (Explainability)":
    st.title("Drivers of Demand – Model Explainability")

    st.markdown(
        """
        To make the model understandable to business users, we use **SHAP** values
        (SHapley Additive exPlanations).  
        SHAP shows how each feature (for example: **Promo**, **Day of Week**, **Lagged Sales**)
        pushes the forecast **up or down**.
        """
    )

    st.markdown(
        """
        **How to use this section (recommended workflow):**
        1. From the notebook, save your SHAP summary plot as an image  
           (e.g., `deployment/shap_summary.png`).  
        2. The dashboard will display it below for planners.
        """
    )

    shap_image_path = os.path.join(DEPLOY_DIR, "shap_summary.png")
    if os.path.exists(shap_image_path):
        st.image(shap_image_path, caption="SHAP Summary: Most Important Drivers of Demand")
    else:
        st.info(
            "SHAP summary image not found. Save it as "
            "`deployment/shap_summary.png` from your notebook to see it here."
        )

    st.markdown(
        """
        In plain language, this helps planners answer questions like:
        *“Are promotions, store traffic, or day-of-week driving most of the demand?”*
        and  
        *“Why did the model predict higher or lower sales for a given day?”*
        """
    )
